version: '3.8'

services:
  app:
    build: .
    container_name: my_laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_KEY=base64:vVb/4JVp0cuy4+oqEucfUQbGVDFqPQkr1cHcoHRB3Ks=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=inventory_management
      - DB_USERNAME=root
      - DB_PASSWORD=root
  db:
    image: mysql:8.0
    container_name: my_mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=inventory_management
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
